<?php
/**
 * @category    ClassyLlama
 * @copyright   Copyright (c) 2017 Classy Llama
 */

/** @var $block \Magento\Catalog\Block\Product\Image */

$altImageUrl = $block->getAltImageUrl();
?>

<span class="product-image-container"
      style="width:<?= $block->getWidth()?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?= ($block->getRatio() * 100); ?>%;">
        <?php if($altImageUrl): ?>
            <img class="product-image-photo alt-image"
                <?= $block->getCustomAttributes(); ?>
                 src="<?= $altImageUrl ?>"
                 width="<?= $block->getResizedImageWidth(); ?>"
                 height="<?= $block->getResizedImageHeight(); ?>"
                 alt="<?= $block->stripTags($block->getLabel(), null, true); ?>"/>
        <?php endif; ?>
        <img class="product-image-photo<?= $altImageUrl ? '' : ' no-alt-image' ?>"
            <?= $block->getCustomAttributes(); ?>
             src="<?= $block->getImageUrl(); ?>"
             width="<?= $block->getResizedImageWidth(); ?>"
             height="<?= $block->getResizedImageHeight(); ?>"
             alt="<?= $block->stripTags($block->getLabel(), null, true); ?>"/>
    </span>
</span>
